docs: update READMEs and remove examples

diff --git a/nextjs/Dockerfile b/nextjs/Dockerfile
--- a/nextjs/Dockerfile
+++ b/nextjs/Dockerfile
@@ -7,11 +7,11 @@ RUN apk add --no-cache libc6-compat
 COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
 
 RUN \
-    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-    elif [ -f package-lock.json ]; then npm ci; \
-    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
-    else echo "Lockfile not found." && exit 1; \
-    fi
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 FROM base AS builder
 
@@ -19,14 +19,11 @@ COPY --from=deps /app/refine/node_modules ./node_modules
 
 COPY . .
 
-ENV NEXT_TELEMETRY_DISABLED 1
-
 RUN npm run build
 
 FROM base AS runner
 
 ENV NODE_ENV production
-ENV NEXT_TELEMETRY_DISABLED 1
 
 COPY --from=builder /app/refine/public ./public
 
diff --git a/vite/Dockerfile.nginx b/vite/Dockerfile.nginx
--- a/vite/Dockerfile.nginx
+++ b/vite/Dockerfile.nginx
@@ -5,11 +5,11 @@ FROM base as deps
 COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
 
 RUN \
-    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-    elif [ -f package-lock.json ]; then npm ci; \
-    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
-    else echo "Lockfile not found." && exit 1; \
-    fi
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 FROM base as builder
 
